# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  # Flux-Kustomizations
  - kube-prometheus-stack/install.yaml
  - grafana/install.yaml
