version: "3"
set:
  - pipefail
shopt:
  - globstar
vars:
  ROOT_DIR: "{{.ROOT_DIR}}"
  KUBERNETES_ROOT: "{{.ROOT_DIR}}/k8s"
includes:
  bootstrap: .taskfiles/bootstrap
  volsync: .taskfiles/volsync
tasks:
  default:
    silent: true
    cmd: task -l
  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
