# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../components/common
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  # Flux-Kustomizations
  - snapshot-controller/install.yaml
  - volsync/install.yaml
  - openebs/install.yaml
