---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAhBmOJloL2z4yxEYpJiySVyEg8JylEL2bNI5FnvmuSg0zO6V/UESS3JYfFhCBItp50HQeb4SBs0a/qvgChYVfVt8GUCYBvKkUZRnMoSq4++uqZmX4IzQcUUaDXZQYpzXkPOq6UlH6JtrydS7Z+kOUIdgji7U1gTpuN7kqlqusJBRG90pIaWKFFnTxXc3R9zo7oCFZpuj8x3DntGFLr2uDreb42Tk2EiARmUMxZI1w9IS6mj8n5zgZ2/urP3670mCS5e3wlYvJzlAMkGrPSwoq/YCjeCTMa491tcZG+3wsMQTQ03xDd7DLsCTOsjEQwGflk6Slfva21B/FyxHFsExYK9/9w5DdaXCmkhJqbuAF+ikqExz3lnGVe70V2fg87vpi3iNzas0E2m6FZ3SWK2y7F0cMbswNycuLRvVoEqRF9lO1dtnd6gqLW/PkhWFglh0zptdsQqzW3Ajd1BIPUta8sS6I6NBpv95YU46WwdlgFZtskSlS64RLxuWEeOYOKhGXNIq0RPJl5meVeBqGrsFVwkRGKKvnuWx4j/QiA8R/A2FCIoZYnvSVlYq0dG1Xj6GtW3oXBdZXY+btrvaPgY0u6pvRld93zwrzkov09rEdREF6pfwB1pAIevaW0WMHOE21pB+/guyLO/jcOVUeNqbjXEwWuwvHN+CVzYzDVsBQZO5oKB4o+DAQeKkQXTrEIrBdh1vqD6dtwv1ck6xbCkA==
    admin-user: AgBJ6WlbpsXr+YCk08mNHS9SZZnIQ1MSX3keGmPZk6e8sRHIVmCWoILIjVBxXgt7b/4fiVP8HRSfVHU51828Shso9rIoJ2MKtwRSJ2L99SmSNlQh35PQ8Y5lQavBnocw3iYkgrmHC90K/ckFYzNpsiXKDRFUeofyMiPZoIX/iiOzJFFaQTVtTrX/Jxe44HRfZDtotU7VTzQAtL2sWN8Us78ZZZ+vwL5wVnfuLlfcbShHiWda41yvVGBVllKoH9zASzPmIqmWHBETLE0jHpdGn5dZiWUKPwa+2NlKvSE9Wjw0wmrnljqZTxy1tujdNNk5D2laL+oTOu3SBj2GNkl5tGVG3Bk7U8L1RTtCxtVeJbw9EUYLFiArbDZCpZnPhEBqZlE6zSp3HEENxSZZjjVrzO0cyLkOc+L98vZqY7KpiN1ueQ827dzFlfWEtpNI6DwAF7jXRU1z+MyLffxIUhl4YjkKlh1cZfho50b0BN7GYttJO0PMa9hP2D16ihI1PwXIzZs8fcCjsSxRZGCgKA6Uc26RyiteB+BkyTVTJqrAWOr3V94gbA7h27LYGiwriSLycMxBbW3F7tOjr2GL00dq/RKvOLBmj5HhlwVykrOYiqWEUUxzY7L/wuEjuygfbc2SPgn7d61lMjdouV9q2NnLO7LgkYOoHu2NswZXG+UjjFJxPzUqkMMK64QDkE8jwGUNJtdQK/ArzQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: observability
