apiVersion: v1
kind: secret
metadata:
  name: grafana-secret
  namespace: observability
data:
  admin-password: ENC[AES256_GCM,data:MAjgfhyQSlyvLErJQIInNR4v+24=,iv:vQJpVUyH6BOf26DPgJpHmgG7IAG3YMRRTyBFHdzYSWo=,tag:/QXIcygG6dDOl4eTBi/T/A==,type:str]
  admin-user: ENC[AES256_GCM,data:tVP+9su3Sig=,iv:uxPvA4Pe+AezmUtHHpLizYiFf33NmpA/IVKKmUlbicY=,tag:ZwJCzXBkp3AV5ce4GuAquw==,type:str]
sops:
  age:
    - recipient: age1023mc3alej5xff6w5xcdf8pwkma4qedtlyg4dqtknvs54vu87qzqlmxsgc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOUlYd1Y3TThXNGFRT3Zi
        RGYvbFIzeGUwdzY1WHdCSU1VaEF0MGt2eEVZCkRKMWdKbG0xdHUrOXFGNTRaSzNZ
        YW9VTS93eHpSL2dibU5Ob1g0Z0RBMU0KLS0tIEVkeEN6bTlZNXdJSHJuRm1iVGFj
        WnVEWE4zTDJVSWZJdlVXK3lHT2gwcU0Kk+Q372YV2X6xfkLuhBLe+4y7OCvBQBS3
        ejp5BZg0PWnUcQrZrAbN4vEdCARaYnaqanAGPDHUBfxOOOE6SdldJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-07T07:16:07Z"
  mac: ENC[AES256_GCM,data:52bb1JkHWgXI57W9n2WP5bE/Yhx6sM+whjpiMcZDmSKfnJd5eQVG29TbQSjypliiivL18z0dLHrGTofW0yZmnpTcbJd1HNSIPTQIkwnfjMr28doyd9YlVV9vNZX8z3tSxQHoeZ/yZ+qXagbPqAOocfQkOFqvZXdXirTSbmZsi/A=,iv:v2ZHMk4R41XSZG9Teagq04hF8y0M9VfhsPrQ/HogWMo=,tag:Nqmz8Yg2aq3Drh7is8M1JA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
